Bloggie.Web/Pages/Admin/Blogs/Add.cshtml.cs
using Azure;
using Bloggie.Web.Data;
using Bloggie.Web.Models.Domain;
using Bloggie.Web.Models.ViewModels;
using Bloggie.Web.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Text.Json;

namespace Bloggie.Web.Pages.Admin.Blogs
{
    [Authorize(Roles = "Admin")]
    public class AddModel : PageModel
    {
        [BindProperty]
        public AddBlogPost AddBlogPostRequest { get; set; }
        public IBlogPostRepository BlogPostRepository { get; }
        [BindProperty]
        public string Tags { get; set; }

        //create constructor 
        public AddModel(IBlogPostRepository blogPostRepository)
        {
            BlogPostRepository = blogPostRepository;
        }
        public void OnGet()
        {
        }
        public async Task<IActionResult> OnPost() {
            BlogPost blogpost = new BlogPost()
            {
                Heading = AddBlogPostRequest.Heading,
                PageTitle = AddBlogPostRequest.PageTitle,
                Content = AddBlogPostRequest.Content,
                ShortDescription = AddBlogPostRequest.ShortDescription,
                FeaturedImageUrl = AddBlogPostRequest.FeaturedImageUrl,
                UrlHandle = AddBlogPostRequest.UrlHandle,
                PublishedDate = AddBlogPostRequest.PublishedDate,
                Author = AddBlogPostRequest.Author,
                Visible = AddBlogPostRequest.Visible,
                tags = new List<Tag>(Tags.Split(',').Select(x => new Tag() { Name = x.Trim() }))
            };
            await this.BlogPostRepository.AddBlogPostAsync(blogpost);
            var jsonNotification = new Notification()
            {
                Message = "BlogBost was successfully Created",
                Type = Enums.NotificationType.Success
            };

            TempData["Notification"] = JsonSerializer.Serialize(jsonNotification);


            return RedirectToPage("/admin/blogs/list");
        }
    }
}

Bloggie.Web/Pages/Admin/Blogs/List.cshtml.cs
using Bloggie.Web.Data;
using Bloggie.Web.Models.Domain;
using Bloggie.Web.Models.ViewModels;
using Bloggie.Web.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Text.Json;

namespace Bloggie.Web.Pages.Admin.Blogs
{
    [Authorize(Roles = "Admin")]
    public class ListModel : PageModel
    {

        public List<BlogPost> blogPosts;

        public ListModel(IBlogPostRepository blogPostRepository)
        {
            BlogPostRepository = blogPostRepository;
        }

        public IBlogPostRepository BlogPostRepository { get; }

        public async Task OnGet()
        {
            var jsonNotification = (string)TempData["Notification"];
            if (jsonNotification!= null) { 

                ViewData["Notification"] = JsonSerializer.Deserialize<Notification>(jsonNotification); 

            }
            blogPosts = (await this.BlogPostRepository.GetAllBlogPostsAsync()).ToList();
        }
    }
}

Bloggie.Web/Pages/Admin/Blogs/edit.cshtml.cs
using Bloggie.Web.Data;
using Bloggie.Web.Models.Domain;
using Bloggie.Web.Models.ViewModels;
using Bloggie.Web.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Text.Json;

namespace Bloggie.Web.Pages.Admin.Blogs
{
    [Authorize(Roles = "Admin")]
    public class editModel : PageModel
    {
        [BindProperty]
        public BlogPost? BlogPost { set; get; }
        public IBlogPostRepository BlogPostRepository { get; }

        public editModel(IBlogPostRepository BlogPostRepository)
        {
            this.BlogPostRepository = BlogPostRepository;
        }
        [BindProperty]
        public String Tags { get; set; }

        public async Task OnGet(Guid id)
        {
            BlogPost = await this.BlogPostRepository.GetBlogPostByIdAsync(id);
            if (BlogPost!=null && BlogPost.tags != null) {
                //Tags = BlogPost.tags.Select(x => x.Name).Aggregate((x, y) => x + ", " + y);
                Tags = string.Join(", ", BlogPost.tags.Select(x=>x.Name));
            }
        }
        public async Task<IActionResult> OnPostEdit()
        {
            try
            {
                BlogPost.tags = new List<Tag>(Tags.Split(',').Select(x => new Tag() { Name = x.Trim() }));
                await this.BlogPostRepository.UpdateBlogPostAsync(BlogPost);
                ViewData["Notification"] = new Notification()
                {
                    Message = "Record was successfully saved",
                    Type = Enums.NotificationType.Success
                };
            }
            catch (Exception)
            {
                ViewData["Notification"] = new Notification()
                {
                    Message = "Something went wrong!",
                    Type = Enums.NotificationType.Error
                };
            }
            return Page();
            //return RedirectToPage("/admin/blogs/list",ViewData);
        }
        public async Task<IActionResult> OnPostDelete()
        {
            bool deleted =  await this.BlogPostRepository.DeleteBlogPostAsync(BlogPost.Id);
            if (deleted)
        {
                var jsonNotification = new Notification()
                {
                    Message = "BlogBost was successfully Deleted",
                    Type = Enums.NotificationType.Info
                };

                TempData["Notification"] = JsonSerializer.Serialize(jsonNotification);
                return RedirectToPage("/admin/blogs/list");
            }
            return Page();
        }
    }
}

Bloggie.Web/Pages/Blog/details.cshtml.cs
using Bloggie.Web.Models.Domain;
using Bloggie.Web.Repositories;
using Bloggie.Web.Repositories.Likes;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;

namespace Bloggie.Web.Pages.Blog
{
    public class detailsModel : PageModel
    {
        private readonly IBlogPostRepository _blogPostRepository;
        private readonly IBlogPostLikeRepository _blogPostLikeRepository;
        public int Likes { get; set; }

        public BlogPost BlogPost { get; set; }
        public detailsModel(IBlogPostRepository blogPostRepository, IBlogPostLikeRepository blogPostLikeRepository)
        {
            _blogPostRepository = blogPostRepository;
            _blogPostLikeRepository = blogPostLikeRepository;
        }
        public async Task<IActionResult> OnGet(string UrlHandle)
        {
            BlogPost = await _blogPostRepository.GetBlogPostByUrlAsync(UrlHandle);
            if (BlogPost != null && BlogPost.Id != null)
            {
                Likes = await _blogPostLikeRepository.GetTotalLikesForBlog(BlogPost.Id);
            }
            else {
                Likes = 0;            
            }
                return Page();
        }
    }
}

Bloggie.Web/Pages/Admin/Blogs/Add.cshtml
@page
@model Bloggie.Web.Pages.Admin.Blogs.AddModel
@{
}
<div class="bg-secondary bg-opacity-10 py-2 mb-5">
    <div class="container">
        <h1>Add Blog Post</h1>
    </div>
</div>

<div>
    <div class="container">
        <form method="post">
            <div class="mb-3">
                <label for="heading" class="form-label">Heading</label>
                <input type="text" class="form-control" id="heading" asp-for="AddBlogPostRequest.Heading">
            </div>
            <div class="mb-3">
                <label for="pageTitle" class="form-label">Page Title</label>
                <input type="text" class="form-control" id="pageTitle" asp-for="AddBlogPostRequest.PageTitle">
            </div>
            <div class="mb-3">
                <label for="content" class="form-label">Content</label>
                <textarea class="form-control" id="content" asp-for="AddBlogPostRequest.Content"></textarea>
            </div>
            <div class="mb-3">
                <label for="shortDescription" class="form-label">Short Description</label>
                <input type="text" class="form-control" id="shortDescription" asp-for="AddBlogPostRequest.ShortDescription">
            </div>
            <div class="mb-3">
                <label for="featuredImageUpload" class="form-label">Featured Image Upload</label>
                <input type="file"  id="featuredImageUpload">
                <img src="" id="featuredImageDisplay" style="display:none; width:300px;" />
            </div>
            <div class="mb-3">
                <label for="featuredImageUrl" class="form-label">Featured Image URL</label>
                <input type="text" class="form-control" id="featuredImageUrl" asp-for="AddBlogPostRequest.FeaturedImageUrl">
            </div>
            <div class="mb-3">
                <label for="urlHandle" class="form-label">URL Handle</label>
                <input type="text" class="form-control" id="urlHandle" asp-for="AddBlogPostRequest.UrlHandle">
            </div>
            <div class="mb-3">
                <label for="publishedDate" class="form-label">Published Date</label>
                <input type="date" class="form-control" id="publishedDate" asp-for="AddBlogPostRequest.PublishedDate">
            </div>
            <div class="mb-3">
                <label for="author" class="form-label">Author</label>
                <input type="text" class="form-control" id="author" asp-for="AddBlogPostRequest.Author">
            </div>
            <div class="mb-3">
                <label for="tags" class="form-label">Tags (comma separated)</label>
                <input type="text" class="form-control" id="tags" asp-for="Tags" />
            </div>
            <div class="form-check mb-3">
                <input class="form-check-input" type="checkbox" id="isVisible" asp-for="AddBlogPostRequest.Visible">
                <label class="form-check-label" for="isVisible">
                    Is Visible
                </label>
            </div>
            <div class="mb-3">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>
    </div>
</div>
@section Scripts{
    <script>
        var editor = new FroalaEditor('#content',{
            imageUploadURL:'/api/images'            
        });

        const featuredImageUploadElement = document.querySelector('#featuredImageUpload');
        const featureImageDisplay = document.querySelector('#featuredImageDisplay');
        const featureImageUrl = document.querySelector('#featuredImageUrl');

        featuredImageUploadElement.addEventListener('change',async function (event) {
            const file = event.target.files[0];

            if (file) {
                let data = new FormData();
                data.append('file', file);

                await fetch('/api/images', {
                    method: 'POST',
                    headers: {
                        'Accept': '*/*'
                    },
                    body: data
                }).then(response => response.json())
                .then(data => {
                    if (data && data.link) {
                        featureImageUrl.value = data.link;
                        featureImageDisplay.src = data.link;
                        featureImageDisplay.style.display = 'block';
                    } else {
                        console.error('Error uploading image:', data);
                        featureImageDisplay.style.display = 'none';
                    }
                }).catch(error => {
                    console.error('Error uploading image:', error);
                });
            }
        });
    </script>
}

Bloggie.Web/Pages/Admin/Blogs/List.cshtml
@page
@model Bloggie.Web.Pages.Admin.Blogs.ListModel
@{
}
<div class="bg-secondary bg-opacity-10 py-2 mb-5">
    <div class="container">
        <h1>Blog Posts</h1>
    </div>
</div>
<partial name="_Notification">
@if (Model.blogPosts != null && Model.blogPosts.Any()){
<div class="container">
    <table class="table">
        <thead>
            <tr>
                <td>Id</td>
                <td>Heading</td>
                <td> </td>
            </tr>
        </thead>
        <tbody>
            @foreach (var blogPost in Model.blogPosts)
            {
                <tr>
                    <td>@blogPost.Id</td>
                    <td>@blogPost.Heading</td>
                    <td><a href="/admin/blogs/edit/@blogPost.Id">View</a></td>
                </tr>
            }
        </tbody>
    </table>
    </div>
}
else
{
    <div class="container">
        <p>no blog post were found!</p
    </div>    
}

Bloggie.Web/Pages/Admin/Blogs/edit.cshtml
@page "{id:guid}"
@model Bloggie.Web.Pages.Admin.Blogs.editModel
@{
}
<div class="bg-secondary bg-opacity-10 py-2 mb-5">
    <div class="container">
        <h1>Edit Blog Post</h1>
    </div>
</div>
    <partial name="_Notification">
    @if (Model.BlogPost != null )
    {
        <div>
            <div class="container">
                <form method="post">
                    <div class="mb-3">
                        <label for="id" class="form-label">Heading</label>
                        <input type="text" class="form-control" id="id" asp-for="BlogPost.Id" readonly>
                    </div>
                    <div class="mb-3">
                        <label for="heading" class="form-label">Heading</label>
                        <input type="text" class="form-control" id="heading" asp-for="BlogPost.Heading">
                    </div>
                    <div class="mb-3">
                        <label for="pageTitle" class="form-label">Page Title</label>
                        <input type="text" class="form-control" id="pageTitle" asp-for="BlogPost.PageTitle">
                    </div>
                    <div class="mb-3">
                        <label for="content" class="form-label">Content</label>
                        <textarea class="form-control" id="content" asp-for="BlogPost.Content"></textarea>
                    </div>
                    <div class="mb-3">
                        <label for="shortDescription" class="form-label">Short Description</label>
                        <input type="text" class="form-control" id="shortDescription" asp-for="BlogPost.ShortDescription">
                    </div>
                    <div class="mb-3">
                        <label for="featuredImageUpload" class="form-label">Featured Image Upload</label>
                        <input type="file"  id="featuredImageUpload">
                        @if (Model.BlogPost.FeaturedImageUrl != null)
                        {
                            <img src="@Model.BlogPost.FeaturedImageUrl" id="featuredImageDisplay" style="width:300px;" />
                        }
                        else
                        {
                            <img src="" id="featuredImageDisplay" style="display:none; width:300px;" />                            
                        }
            </div>
            <div class="mb-3">
                <label for="featuredImageUrl" class="form-label">Featured Image URL</label>
                <input type="text" class="form-control" id="featuredImageUrl" asp-for="BlogPost.FeaturedImageUrl">
            </div>
            <div class="mb-3">
                <label for="urlHandle" class="form-label">URL Handle</label>
                <input type="text" class="form-control" id="urlHandle" asp-for="BlogPost.UrlHandle">
            </div>
            <div class="mb-3">
                <label for="publishedDate" class="form-label">Published Date</label>
                <input type="date" class="form-control" id="publishedDate" asp-for="BlogPost.PublishedDate">
            </div>
            <div class="mb-3">
                <label for="author" class="form-label">Author</label>
                <input type="text" class="form-control" id="author" asp-for="BlogPost.Author">
            </div>
            <div class="mb-3">
                <label for="tags" class="form-label">Tags (comma separated)</label>
                <input type="text" class="form-control" id="tags" asp-for="Tags" />
            </div>
            <div class="form-check mb-3">
                <input class="form-check-input" type="checkbox" id="isVisible" asp-for="BlogPost.Visible">
                <label class="form-check-label" for="isVisible">
                    Is Visible
                </label>
            </div>
            <div class="mb-3 d-flex justify-content-between">
                <button type="submit" class="btn btn-danger" asp-page-handler="Delete">Delete</button>
                <button type="submit" class="btn btn-primary" asp-page-handler="Edit">Submit</button>
            </div>
        </form>
    </div>
</div>
    }
else
{
    <div class="container">
        <p>no blogpost is found</p
    </div>    
}
@section Scripts{
    <script>
        var editor = new FroalaEditor('#content',{
            imageUploadURL:'/api/images'            
        });

        const featuredImageUploadElement = document.querySelector('#featuredImageUpload');
        const featureImageDisplay = document.querySelector('#featuredImageDisplay');
        const featureImageUrl = document.querySelector('#featuredImageUrl');

        featuredImageUploadElement.addEventListener('change',async function (event) {
            const file = event.target.files[0];

            if (file) {
                let data = new FormData();
                data.append('file', file);

                await fetch('/api/images', {
                    method: 'POST',
                    headers: {
                        'Accept': '*/*'
                    },
                    body: data
                }).then(response => response.json())
                .then(data => {
                    if (data && data.link) {
                        featureImageUrl.value = data.link;
                        featureImageDisplay.src = data.link;
                        featureImageDisplay.style.display = 'block';
                    } else {
                        console.error('Error uploading image:', data);
                        featureImageDisplay.style.display = 'none';
                    }
                }).catch(error => {
                    console.error('Error uploading image:', error);
                });
            }
        });
    </script>
}